# Generation of Kubernetes YAML is still under development!
#
# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-1.6.1
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2019-10-15T12:15:42Z"
  labels:
    app: pod01
  name: pod01
spec:
  containers:
  - command:
    - bash
    env:
    - name: PATH
      value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - name: TERM
      value: xterm
    - name: HOSTNAME
      value: pod01
    - name: container
      value: oci
    image: registry.access.redhat.com/ubi7:latest
    name: festivejang
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities: {}
      privileged: false
      readOnlyRootFilesystem: false
    stdin: true
    workingDir: /
  - command:
    - bash
    env:
    - name: PATH
      value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - name: TERM
      value: xterm
    - name: HOSTNAME
      value: pod01
    - name: container
      value: oci
    image: registry.access.redhat.com/ubi8:latest
    name: practicaljang
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities: {}
      privileged: false
      readOnlyRootFilesystem: false
    stdin: true
    workingDir: /
status: {}

