# Generation of Kubernetes YAML is still under development!
#
# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-1.6.1
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2019-10-16T00:20:50Z"
  labels:
    app: recognizer
  name: recognizer
spec:
  containers:
  - command:
    - /bin/bash
    env:
    - name: PATH
      value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - name: TERM
      value: xterm
    - name: HOSTNAME
      value: recognizer
    - name: container
      value: oci
    image: registry.access.redhat.com/ubi8/ubi:latest
    name: bit
    ports:
    - containerPort: 80
      hostPort: 8080
      protocol: TCP
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities: {}
      privileged: false
      readOnlyRootFilesystem: false
    stdin: true
    workingDir: /
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-10-16T00:20:50Z"
  labels:
    app: recognizer
  name: recognizer
spec:
  ports:
  - name: "80"
    nodePort: 32710
    port: 80
    protocol: TCP
    targetPort: 0
  selector:
    app: recognizer
  type: NodePort
status:
  loadBalancer: {}

